name: "Testing Workflow"

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  application:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 21.2.0
          cache: yarn

      - name: Install
        run: yarn install

      - name: Tests
        run: yarn test
        env:
          AUTHORIZATION_KEY: ${{ secrets.AUTHORIZATION_KEY }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
